index: README.md
style:
  load:
    - sources/style.css
  themes:
    dark: https://files.jojojux.de/api/readme/themes/dark.css
    light: https://files.jojojux.de/api/readme/themes/light.css
  default theme: none
folders:
  - sources
files:
  - README.md
  - README.de.md
  - sources/*
