index: README.md
style:
  load:
    - sources/style.css
  themes:
    dark: sources/themes/dark.css
    light: sources/themes/light.css
  default theme: dark
folders:
  - sources
files:
  - README.md
  - README.de.md
  - sources/**
