name: Update Docs Folder Contents

on:
  push:
    branches:
      - 'main'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          
      - name: Install Python modules
        run: |
          python -m pip -r autodocs/requirements.txt
          
      - name: Run Python script
        run: |
          cd autodocs
          python update.py
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update docs" -a
          
      - name: Push files
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
